# FAIL

fn f(x: int) -> int {
  return x + 1
}

print(x)
